import { Bell, Menu, Moon, Search, Sun } from "lucide-react";
import { useLocation } from "react-router-dom";
import { adminRoleLabels, adminRoles, type AdminRole, type AdminTheme } from "../../types";
import { useAdminAuth } from "../../lib/auth";

export function AdminTopbar({ onMenu, theme, setTheme }: { onMenu: () => void; theme: AdminTheme; setTheme: (theme: AdminTheme) => void }) {
  const location = useLocation();
  const { user, setRolePreview } = useAdminAuth();
  const crumb = location.pathname.replace("/admin", "Admin").split("/").filter(Boolean).join(" / ") || "Admin";
  return <header className="sticky top-0 z-30 border-b border-divider bg-glass backdrop-blur-xl"><div className="flex min-h-16 items-center justify-between gap-4 px-4 lg:px-6"><div className="flex items-center gap-3"><button type="button" onClick={onMenu} className="rounded-tokenPill p-2 text-primary hover:bg-primary-light lg:hidden" aria-label="Open admin menu"><Menu size={22} /></button><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-text-muted">{crumb}</p><h1 className="text-xl font-black text-primary">Dashboard Console</h1></div></div><label className="relative hidden flex-1 max-w-md lg:block"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-text-muted" size={18} /><span className="sr-only">Search everywhere</span><input className="form-field h-11 w-full rounded-tokenPill pl-11" placeholder="Search courses, leads, users..." /></label><div className="flex items-center gap-2"><select value={user?.role} onChange={(event) => setRolePreview(event.target.value as AdminRole)} className="hidden rounded-tokenPill border border-border bg-card px-3 py-2 text-sm font-bold text-primary lg:block" aria-label="Preview role">{adminRoles.map((role) => <option key={role} value={role}>{adminRoleLabels[role]}</option>)}</select><button type="button" onClick={() => setTheme(theme === "light" ? "dark" : "light")} className="grid h-10 w-10 place-items-center rounded-tokenPill border border-border bg-card text-primary" aria-label="Toggle theme">{theme === "light" ? <Moon size={18} /> : <Sun size={18} />}</button><button type="button" className="grid h-10 w-10 place-items-center rounded-tokenPill border border-border bg-card text-primary" aria-label="Notifications"><Bell size={18} /></button><div className="grid h-10 w-10 place-items-center rounded-tokenPill bg-primary text-sm font-black text-text-inverse">{user?.avatarInitials}</div></div></div></header>;
}
